project:
  type: website
  output-dir: docs
website:
  title: "Blockchain news feed"
  navbar:
    right:
      - about.ipynb
      - icon: github
        href: https://github.com/masapasa/mina
      - icon: twitter
        href: https://twitter.com/aswinpy
format:
  html:
    css: styles.css
    toc: true
    monobackgroundcolor: '#FAFAFA'

